import { Category, EPass, DashboardStats } from '../types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Medical Emergency',
    description: 'For urgent medical situations requiring movement during curfew',
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Essential Services',
    description: 'For workers in essential services (healthcare, utilities, etc.)',
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Supply Transport',
    description: 'For transportation of essential supplies and goods',
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Government Work',
    description: 'For government officials and employees on duty',
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
];

export const generateMockPasses = (): EPass[] => [
  {
    id: '1',
    userId: 'user1',
    categoryId: '1',
    fullName: 'John Doe',
    email: 'john.doe@email.com',
    phone: '+1234567890',
    address: '123 Main Street, Cityville',
    destination: 'General Hospital',
    purpose: 'Emergency medical treatment for family member',
    startDate: '2025-01-15',
    endDate: '2025-01-15',
    startTime: '20:00',
    endTime: '06:00',
    status: 'approved',
    adminNotes: 'Medical emergency verified. Pass approved.',
    approvedBy: 'admin',
    appliedAt: '2025-01-14T10:30:00Z',
    updatedAt: '2025-01-14T11:00:00Z',
  },
  {
    id: '2',
    userId: 'user2',
    categoryId: '2',
    fullName: 'Jane Smith',
    email: 'jane.smith@email.com',
    phone: '+1234567891',
    address: '456 Oak Avenue, Townsburg',
    destination: 'Water Treatment Plant',
    purpose: 'Emergency maintenance of water supply system',
    startDate: '2025-01-16',
    endDate: '2025-01-16',
    startTime: '22:00',
    endTime: '05:00',
    status: 'pending',
    appliedAt: '2025-01-15T14:20:00Z',
    updatedAt: '2025-01-15T14:20:00Z',
  },
  {
    id: '3',
    userId: 'user3',
    categoryId: '3',
    fullName: 'Mike Johnson',
    email: 'mike.johnson@email.com',
    phone: '+1234567892',
    address: '789 Pine Road, Villageton',
    destination: 'Central Food Distribution Center',
    purpose: 'Delivery of essential food supplies to distribution center',
    startDate: '2025-01-17',
    endDate: '2025-01-17',
    startTime: '21:00',
    endTime: '04:00',
    status: 'rejected',
    adminNotes: 'Documentation incomplete. Please resubmit with proper vehicle registration.',
    approvedBy: 'admin',
    appliedAt: '2025-01-14T16:45:00Z',
    updatedAt: '2025-01-14T18:30:00Z',
  },
];

export const getDashboardStats = (passes: EPass[]): DashboardStats => ({
  totalApplications: passes.length,
  pendingApplications: passes.filter(p => p.status === 'pending').length,
  approvedApplications: passes.filter(p => p.status === 'approved').length,
  rejectedApplications: passes.filter(p => p.status === 'rejected').length,
  totalUsers: new Set(passes.map(p => p.userId)).size,
  activeCategories: categories.filter(c => c.isActive).length,
});